monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
            excluded_404s:
                # regex: exclude all 404 errors from the logs
                - ^/
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        app:
            type: stream
            path: "%kernel.logs_dir%/app_%kernel.environment%.log"
            level: info
            channels: ["app"]
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
